### ISSUE TITLE
Controller Sensitivity in GUI (RetroPie)

### ISSUE THREAD

**Issue by PanosPl** [KaosOverride/CapriceRPI#1]
Using the pad to select from the virtual keyboard (and the rest of the GUI) is almost impossible due to the extreme sensitivity of the controller. Can this be ammended?

**Comment by KaosOverride** [comment]
Was it working well some time ago? Do you have a different pad for testing? I have used with all kind of USB pads I have (not many) with no problem. I will take a look if any Raspbian/Retropie lib update can be the issue and try a solution.

**Comment by PanosPl** [comment]
Hi Kaos! Well, I am using an XBOX 360 wired controller. Only the left analog stick works inside the emulator. The dpad not. So when I am trying to navigate inside the virtual keyboard with the analog stick, the sensitivity is crazy high and the selection is impossible. Congratulations for your excellent work btw!

**Comment by KaosOverride** [comment]
I think that gives me a clue, by the way I manage the X Y axis. First I will try to reproduce it with my PS2 USB pads with analog stick (I'm badly used to turn the Dpad digital mode for the analog stick)

**Comment by KaosOverride** [comment]
Ok, it is my great fault. By the heritage from CapriceGP2x, the joystick management is purely digital. The problem with using analog controls is that each axis variation produces an event, but actually continues to set the same direction. I have to take this into account to ignore superfluous information that will generate extra movement at the GUI.
It will be a good incentive to code the controlled repetition of movement at the GUI I was after, and not have to be pressing several times to move through the options.

When I have some time I'll get on it.

**Comment by PanosPl** [comment]
Thank you. I am looking forward to

**Comment by KaosOverride** [comment]
I have done some rework of the whole menu system about input devices. Lot of "Spaghetti Code"  has been reworked to a more maintainable structure, which allows me to do the fix and help future changes. I hope it works as good for all as my PS2 style USB pads in analog mode use for testing.There is also some unnoticeable partial code and changes for future V1.4 that is "there" but deactivated until completion.
Please, tell me if it works fine, and sorry for the late delay for the fix.

**Comment by PanosPl** [comment]
Thank you Kaos! You fixed it! Great job!

**Comment by KaosOverride** [comment]
Thanks to you for the advise!
